import React from 'react'

import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`bg-white text-gray-800 ${inter.className}`}>
            <body className="flex h-screen">
            <main className="flex-grow overflow-hidden">{children}</main>
            </body>
        </html>
    );
}
